

# api_platform:
#   title: 'Symfony REST API'
#   description: 'A Symfony API to manage a simple blog app.'
#   version: '1.0.0'
#   mapping:
#     paths: ['%kernel.project_dir%/src/Entity']

#   formats:
#       jsonld:
#           mime_types:
#               - application/ld+json
#       json:
#           mime_types:
#               - application/json
#       html:
#           mime_types:
#               - text/html
#       jsonhal:
#           mime_types:
#               - application/hal+json
#   error_formats:
#       jsonproblem:
#           mime_types:
#               - application/problem+json
#       jsonld:
#           mime_types:
#               - application/ld+json

  
#   patch_formats:
#     json: ['application/merge-patch+json']
#   swagger:
#     versions: [3]
#     api_keys:
#       apiKey:
#         name: Authorization
#         type: header



api_platform:
  title: 'Symfony REST API'
  description: 'A Symfony API to manage a simple blog app.'
  version: '1.0.0'
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  
